app/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
from . import viewss
from core import views
from django.conf.urls import handler400


# , handler403, handler404, handler500


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'productos', viewss.ProductoViewSet)
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),
                  path('', views.HomeView.as_view(), name='home'),
                  path('contact/', views.ContactView.as_view(), name='contact'),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('profile/', views.ProfilView.as_view(), name='profile'),
                  # path('api/', include(router.urls)),
                  # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = viewss.Error404View.as_view()

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('Tienda/', views.ProductoListView.as_view(), name='product-list'),
    path('Tienda/<slug>/', views.ProductoDetailView.as_view(), name='product-detail'),
    path('incrementar-cantidad/<pk>/', views.AumentarcantidadView.as_view(), name='incrementar-cantidad'),
    path('disminuir-cantidad/<pk>/', views.DisminuirCantidadView.as_view(), name='disminuir-cantidad'),
    path('eliminar-cantidad/<pk>/', views.EliminarCantidadView.as_view(), name='eliminar-cantidad'),
    path('pagar/', views.PagarView.as_view(), name='pagar'),
    path('payment/', views.Payment.as_view(), name='payment'),
    path('gracias/', views.GraciasView.as_view(), name='gracias'),
    path('cofirm-orden/', views.ConfirmOrdenView.as_view(), name='cofirm-orden'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

cart/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Bebidavariacion, Direccion, ordenIten, Producto

User = get_user_model()


class AddToCartForm(forms.ModelForm):
    class Meta:
        model = ordenIten
        fields = ['cantidad', 'bebida']
        queryset = {
            'bebida': Bebidavariacion.objects.none(),
        }
        labels = {
            'cantidad': 'ELIGA LA CANTIDAD DE SU PRODUCTO',
            'bebida': 'ELIGA EL TIPO DE SU BEBIDA',
        }
        help_texts = {
            'cantidad': 'Selecione por favor una cantidad mayor o igual a 1',
            'bebida': 'Selecione por favor un tipo de bebida',
        }

        widgets = {
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'bebida': forms.RadioSelect(attrs={'class': 'form-check-input'}),
        }
        max_values = {
            'cantidad': 100,
        }

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('producto_id')
        producto = Producto.objects.get(id=product_id)
        super().__init__(*args, **kwargs)
        self.fields['bebida'].queryset = producto.avalible_bebida.all()


class AdressForm(forms.Form):
    direccion_de_envio_1 = forms.CharField(required=False,
                                           label='Dirección de envío calle principal',
                                           widget=forms.TextInput(
                                               attrs={'placeholder': ' Ejemplo: Av. de la Constitución'}))

    direccion_de_envio_2 = forms.CharField(required=False,
                                           label='Dirección de envío calle secundaria',
                                           widget=forms.TextInput(attrs={'placeholder': ' Ejemplo: 10 de Agosto'}))
    ciudad_de_envio = forms.CharField(required=False, label='Ciudad de envío',
                                      widget=forms.TextInput(attrs={'placeholder': ' Ejemplo: Guayaquil'}))

    direccion_de_facturacion_1 = forms.CharField(required=False,
                                                 label='Dirección de facturación calle principal',
                                                 widget=forms.TextInput(
                                                     attrs={'placeholder': ' Ejemplo: Av. 8 de Diciembre'}))
    direccion_de_facturacion_2 = forms.CharField(required=False,
                                                 label='Dirección de facturación calle secundaria',
                                                 widget=forms.TextInput(attrs={'placeholder': ' Ejemplo: Colon'}))
    ciudad_de_facturacion = forms.CharField(required=False, label='Ciudad de facturación',
                                            widget=forms.TextInput(attrs={'placeholder': ' Ejemplo: Guayaquil'}))

    selecionar_direccion_de_envio = forms.ModelChoiceField(
        Direccion.objects.none(), required=False, label='Seleccione una dirección para el envío de su compra'
    )
    selecionar_direccion_de_facturacion = forms.ModelChoiceField(
        Direccion.objects.none(), required=False, label='Seleccione una dirección para la facturación de su compra'
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)
        user = User.objects.get(id=user_id)

        direccion_de_envio_qs = Direccion.objects.filter(
            user=user,
            tipo_de_direccion='S'
        )
        direccion_de_Fcacturacion_qs = Direccion.objects.filter(
            user=user,
            tipo_de_direccion='B'
        )

        self.fields['selecionar_direccion_de_envio'].queryset = direccion_de_envio_qs
        self.fields['selecionar_direccion_de_facturacion'].queryset = direccion_de_Fcacturacion_qs

    def clean(self):
        data = self.cleaned_data
        selecionar_direccion_de_envio = data.get('selecionar_direccion_de_envio', None)
        if selecionar_direccion_de_envio is None:
            if not data.get('direccion_de_envio_1', None):
                self.add_error("direccion_de_envio_1", "Por favor complete este campo")

            if not data.get('direccion_de_envio_2', None):
                self.add_error("direccion_de_envio_2", "Por favor complete este campo")

            if not data.get('ciudad_de_envio', None):
                self.add_error("ciudad_de_envio", "Por favor complete este campo")

        selecionar_direccion_de_facturacion = data.get('selecionar_direccion_de_facturacion', None)
        if selecionar_direccion_de_facturacion is None:
            if not data.get("direccion_de_facturacion_1", None):
                self.add_error("direccion_de_facturacion_1", "Por favor complete este campo")

            if not data.get('direccion_de_facturacion_2', None):
                self.add_error("direccion_de_facturacion_2", "Por favor complete este campo")

            if not data.get('ciudad_de_envio', None):
                self.add_error("ciudad_de_facturacion", "Por favor complete este campo")

cart/views.py
import json
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Direccion, Orden, Producto, ordenIten, Pago
from .utlis import get_or_set_or_session
from .forms import AddToCartForm, AdressForm
from django.shortcuts import get_object_or_404, redirect, reverse
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse


class ProductoListView(generic.ListView):
    template_name = 'cart/product_list.html'
    queryset = Producto.objects.all()


class ProductoDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Producto, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductoDetailView, self).get_form_kwargs()
        kwargs["producto_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_or_session(self.request)
        producto = self.get_object()
        # visualizar los datos del formulario

        iten_filter = order.items.filter(
            producto=producto,
            bebida=form.cleaned_data['bebida']
        )
        # si el producto no exxite  existe en el carrito
        if iten_filter.exists():
            item = iten_filter.first()
            if item.cantidad >= 100:
                messages.info(self.request, "No se puede agregar mas de 100 procutos de un mismo producto")
                return redirect("cart:summary")
            item.cantidad += int(form.cleaned_data['cantidad'])
            item.save()
        else:
            new_item = form.save(commit=False)
            new_item.producto = producto
            new_item.order = order
            new_item.save()
            print("Agregar producto al carrito cuando el producto no existe")
        return super(ProductoDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductoDetailView, self).get_context_data(**kwargs)
        context['producto'] = self.get_object()
        return context


class CartView(generic.TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["orden"] = get_or_set_or_session(self.request)
        return context


class AumentarcantidadView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(ordenIten, id=kwargs['pk'])
        if order_item.cantidad >= 100:
            messages.info(self.request, "No se puede agregar mas de 100 procutos de un mismo producto")
            return redirect("cart:summary")
        else:
            order_item.cantidad += 1
            order_item.save()
            return redirect("cart:summary")


class DisminuirCantidadView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(ordenIten, id=kwargs['pk'])
        if order_item.cantidad <= 1:
            order_item.delete()
        else:
            order_item.cantidad -= 1
            order_item.save()
        return redirect("cart:summary")


class EliminarCantidadView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(ordenIten, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:summary")


class PagarView(generic.FormView):
    template_name = 'cart/pagar.html'
    form_class = AdressForm

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        orden = get_or_set_or_session(self.request)
        selecionar_direccion_de_envio = form.cleaned_data.get('selecionar_direccion_de_envio')
        selecionar_direccion_de_facturacion = form.cleaned_data.get('selecionar_direccion_de_facturacion')

        if selecionar_direccion_de_facturacion:
            orden.direccion_de_facturacion = selecionar_direccion_de_facturacion
        else:
            direccion = Direccion.objects.create(
                tipo_de_direccion='B',
                user=self.request.user,
                direccion_line_1=form.cleaned_data['direccion_de_facturacion_1'],
                direccion_line_2=form.cleaned_data['direccion_de_facturacion_2'],
                ciudad=form.cleaned_data['ciudad_de_facturacion'],
            )
            orden.direccion_de_facturacion = direccion

        if selecionar_direccion_de_envio:
            orden.direccion_de_envio = selecionar_direccion_de_envio
        else:
            direccion = Direccion.objects.create(
                tipo_de_direccion='S',
                user=self.request.user,
                direccion_line_1=form.cleaned_data['direccion_de_envio_1'],
                direccion_line_2=form.cleaned_data['direccion_de_envio_2'],
                ciudad=form.cleaned_data['ciudad_de_envio'],
            )
            orden.direccion_de_envio = direccion

        orden.save()

        messages.info(self.request, "Has agregado correctamente tus direcciones")
        return super(PagarView, self).form_valid(form)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(PagarView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(PagarView, self).get_context_data(**kwargs)
        context["orden"] = get_or_set_or_session(self.request)
        return context


class Payment(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(Payment, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID
        context['orden'] = get_or_set_or_session(self.request)
        context['CALLBACK_URL'] = reverse('cart:cofirm-orden')
        return context


class ConfirmOrdenView(generic.View):
    def post(self, request, *args, **kwargs):
        orden = get_or_set_or_session(request)
        body = json.loads(request.body)
        pago = Pago.objects.create(
            orden=orden,
            sucecesful=True,
            raw_repuesta=json.dump(body),
            total=float(body["purchase_units"][0]["amount"]["value"]),
            metodo_pago='Paypal'
        )
        pago.save()
        orden.ordenn = True
        orden.orden_fecha = datetime.date.today()
        orden.save()
        return reverse('cart:gracias'), JsonResponse({"data": "Success"})


class GraciasView(generic.TemplateView):
    template_name = 'cart/gracias.html'


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Orden.objects.all()
    context_object_name = 'order'

templates/cart/cart.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Carrito</strong>
            </div>
        </div>
    </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row mb-5">

                <div class="col-md-12">
                    <div class=" site-blocks-table">
                        <table class="table text-center">
                            <thead>
                            <tr>
                                <td>Imagen</td>
                                <td>Producto</td>
                                <td>Precio</td>
                                <td>Cantidad</td>
                                <td>Total</td>
                                <td>Acciones</td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in orden.items.all %}
                                <tr>
                                    <td class="product-thumbnail">
                                        <img src="{{ item.producto.image.url }}" class="img-fluid"> </img>
                                    </td>
                                    <td class="product-name">
                                        <h2 class="h5- text-black"> {{ item.producto.title }}</h2>
                                        <small>Tipo de bebida: {{ item.bebida.nombre }}</small>
                                    </td>
                                    <td>${{ item.producto.get_precio }}</td>
                                    <td>
                                        <div class="input-group mb-3" style="max-width:120px;">
                                            <div class="input-group-pretend">
                                                <a href="{% url 'cart:disminuir-cantidad' item.id %}"
                                                   class="btn btn-outline-primary">
                                                    &minus;
                                                </a>
                                            </div>
                                            <input type="text" class="form-control text-center"
                                                   value="{{ item.cantidad }}">
                                            <div class="input-group-append">
                                                <a href="{% url 'cart:incrementar-cantidad' item.id %}"
                                                   class="btn btn-outline-primary">
                                                    &plus;
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                    <td>${{ item.get_total }}</td>
                                    <td>
                                        <a href="{% url 'cart:eliminar-cantidad' item.id %}"
                                           class="btn btn-primary btn-sm">QUITAR</a>
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="6">
                                        No hay productos en su carrito. <a href="{% url 'cart:product-list' %}">
                                        Complete su carrito </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>


            </div>
            {% if orden.items.count > 0 %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="row mb-5">
                            <div class="col-md-12">
                                <a class="btn btn-outline-primary btn-sm btn-block"
                                   href="{% url 'cart:product-list' %}">Complete su carrito</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6" pl-5>
                        <div class="row justify-content-end">
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-12 text-right border-bottom mb-5">
                                        <h3 class="text-black h4 text-uppercase"> Total del Carrito<i
                                                class="fas fa-clipboard-prescription    "></i></h3>
                                    </div>
                                </div>
                                <div class="row mb-5">
                                    <div class="col-mb-6">
                                        <span class="text-black">SubTotal</span>
                                    </div>

                                    <div class="col-md-6 text-right">
                                        <strong class="text-black">${{ orden.get_subtotal }} </strong>
                                    </div>
                                </div>

                                <div class="row mb-5">
                                    <div class="col-mb-6">
                                        <span class="text-black">Total</span>
                                    </div>

                                    <div class="col-md-6 text-right">
                                        <strong class="text-black">${{ orden.get_total }} </strong>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        {% if request.user.is_authenticated %}
                                            <a href="{% url 'cart:pagar' %}"
                                               class="btn btn-warning btn-lg py-3 btn-block">Proceder con el Pago</a>
                                        {% else %}
                                            <a href="{% url 'account_login' %}"
                                               class="btn btn-warning btn-lg py-3 btn-block">Proceder con el Pago</a>
                                        {% endif %}


                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>

                </div>
                </div>
            {% endif %}
    </div>
    </div>




{% endblock content %}

templates/cart/gracias.html
{% extends 'base.html' %}
{% block content %}
    <div class="container text-center">
        <h2> Gracias por su compra su pedido llegará lo más pronto posible <i class="fas fa-heart"></i>
        </h2>
    </div>
{% endblock content %}

templates/cart/pagar.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Carrito </strong>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Pago</strong>
            </div>
        </div>
    </div>
    </div>

    <div class="site-section">
        <div class="container">


            {% if not request.user.is_authenticated %}
                <div class="row mb-5">
                    <div class="col-mb-12">
                        <div class="border p-4 rounded" role="alert">
                            Casi ha terminado su pedido.
                            Para finalizar su orden , porfavor <a href="">Acceder</a> o <a href="">Registrate</a>
                        </div>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" style="width: 90%;" aria-label="90"
                                 aria-valuemin="0" aria-valuemax="100">
                                90% Completado
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-md-0">
                            <h2 class="h3 mb-3 text-black text-center">
                                Detalle de facturación</h2>
                            <hr/>
                            <div class="p-2 p-lg-2">
                                {{ form|crispy }}
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success btn-lg py-3 btn-block">
                                        Proceder con el pago
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="row mb-5">
                                <div class="col-md-12">
                                    <h2 class="h3 mb-3 text-black text-center"> Orden </h2>
                                    <hr>
                                    <div class="p-3 p-lg-5">
                                        <table class="table site-block-order-table mb-5">
                                            <thead>

                                            <td>Producto</td>

                                            <td>Total</td>

                                            </thead>
                                            <tbody>
                                            {% for item in orden.items.all %}
                                                <tr>

                                                    <td>
                                                        {{ item.producto.title }} con {{ item.bebida.nombre }}
                                                        <strong class="mx-2 ">X</strong>{{ item.cantidad }}
                                                    </td>


                                                    <td>${{ item.get_total }}</td>
                                                </tr>

                                            {% endfor %}
                                            <tr>
                                                <td><strong class="text-black font-weight-bold">Subtotal</strong></td>
                                                <td>${{ orden.get_subtotal }}</td>
                                            </tr>
                                            <tr>
                                                <td><strong class="text-black font-weight-bold">Total de la
                                                    Orden</strong></td>
                                                <td><strong
                                                        class="text-black font-weight-bold">${{ orden.get_total }}</strong>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            {% endif %}


        </div>
    </div>



{% endblock content %}

templates/cart/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="bg-light py-3 ">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0">
                    <a href={% url 'home' %}>Inicio</a>
                    <span class="mx-2 mb-0">/</span>
                    <a href="{% url 'cart:product-list' %}"> Tienda </a>
                    <span class="mx-2 mb-0">/</span>
                    <strong class="text-block">{{ producto.title }}</strong>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row mb-5">
                <div class=" col-md-6">
                    <a><img src="{{ producto.image.url }}" class="img-fluid"></a>
                </div>
                <div class="col-md-6 mb-4" data-aos='fade-up'>
                    <h2 class="text-black">{{ producto.title }}</h2>
                    <h4 class="text-black">$ {{ producto.get_precio }} </h4>
                    <p class="text-black">Descripción</p>
                    <p>{{ producto.descripcion }}</p>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type='submit' class="btn btn-sm btn-primary ">Añadir al carrito</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

templates/cart/product_list.html
{% extends "base.html" %}

{% block content %}
    <div class="bg-light py-3 ">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0">
                    <a href="{% url 'home' %}">Inicio</a>
                    <span class="mx-2 mb-0">/</span>
                    <strong class="text-block">Tienda</strong>
                </div>
            </div>
        </div>
    </div>

    <div class="site-section">
        <div class="container">
            <div class="row mb-5">
                {% for product in object_list %}
                    <div class="col-lg-4 col-md-6 mb-4" data-aos='fade-up'>
                        <figure class="block-4-image">
                            <a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}"
                                                                          class="img-fluid"></a>

                        </figure>
                        <div class="bloc-4-text p-4"></div>
                        <a href="{{ product.get_absolute_url }}"><h3>{{ product.title }}</h3></a>
                        <p class="mb-0">{{ product.descripcion }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>


{% endblock content %}