app/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from django.conf.urls.static import static
from rest_framework import routers, serializers, viewsets
from . import viewss
from core import views
from django.conf.urls import handler400


# , handler403, handler404, handler500


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'productos', viewss.ProductoViewSet)
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),
                  path('', views.HomeView.as_view(), name='home'),
                  path('contact/', views.ContactView.as_view(), name='contact'),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('profile/', views.ProfilView.as_view(), name='profile'),
                  # path('api/', include(router.urls)),
                  # path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = viewss.Error404View.as_view()

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('Tienda/', views.ProductoListView.as_view(), name='product-list'),
    path('Tienda/<slug>/', views.ProductoDetailView.as_view(), name='product-detail'),
    path('incrementar-cantidad/<pk>/', views.AumentarcantidadView.as_view(), name='incrementar-cantidad'),
    path('disminuir-cantidad/<pk>/', views.DisminuirCantidadView.as_view(), name='disminuir-cantidad'),
    path('eliminar-cantidad/<pk>/', views.EliminarCantidadView.as_view(), name='eliminar-cantidad'),
    path('pagar/', views.PagarView.as_view(), name='pagar'),
    path('payment/', views.Payment.as_view(), name='payment'),
    path('gracias/', views.GraciasView.as_view(), name='gracias'),
    path('cofirm-orden/', views.ConfirmOrdenView.as_view(), name='cofirm-orden'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

templates/base.html
{% load static %}
{% load cart_templatetags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="WAS" content="3ffbcb6fce65f4f0f8ef2144b4e35254">
    <title>Sabor y Sazón {% block head_title %}{% endblock %}</title>
    {% block extra_head %}

    {% endblock extra_head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.jpg' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.jpg' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.jpg' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.jpg' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.jpg' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.jpg' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.jpg' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.jpg' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.jpg' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.jpg' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.jpg' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.jpg' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.jpg' %}">
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.jpg' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                        <div>
                            <a href="{% url 'home' %}">
                                <img class="img-fluid" src="{% static 'images/logo.jpg' %}" style="max-width: 200px;"/>

                            </a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'profile' %}"><span><i class="fas fa-user"></i></span></a>

                                    {% else %}
                                        <a href="{% url 'account_login' %}"><span><i
                                                class="fas fa-sign-in-alt"></i></span></a>
                                    {% endif %}
                                </li>
                                <li>
                                    <a href="{% url 'cart:summary' %}" class="site-cart">
                                        <span><i class="fas fa-shopping-cart"></i></span>
                                        <span class="count">{{ request | cart_iten_count }}</span>
                                    </a>
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0">
                                    <a href="#" class="site-menu-toggle js-menu-toggle">
                                        <span><i class="fas fa-bars"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

    </header>

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

</div>

{% include 'scripts.html' %}


{% block scripts %}
{% endblock scripts %}

</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="bg-light py-3 ">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mb-0">
                    <a href={% url 'home' %}>Inicio</a>
                    <span class="mx-2 mb-0">/</span>
                    <strong class="text-block">Contacto</strong>
                </div>
            </div>
        </div>
    </div>
    <div class="site-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-7">
                    <h2 class="h3 mb-3 text-black">Ponerse en contacto</h2>
                </div>

                <div class="col-md-7">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" class="btn btn-primary btn-lg btn-block" value="Enviar mensaje"/>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>

                    <i class="fas fa-heart"></i>
                    2023 Por Vitacho
                </p>
            </div>
        </div>
    </div>

</footer>

templates/index.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <div class="site-blocks-cover" style="background-image: url({% static 'images/heros.jpg' %});" data-aos="fade">
        <div class="container">
            <div class="row">
                <div class="col-md-4 pt-5 pt-md-0">
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/navbar.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Inicio</a></li>
            <li><a href="{% url 'cart:product-list' %}">Tienda</a></li>

            {% if request.user.is_staff %}
                <li><a href="/admin">Administración</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/order.html
{% extends "base.html" %}

{% block content %}
    <div class="site-sectino">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-m-12">
                    <a href="{% url 'profile' %}">Back to Profile</a>
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                Order: #{{ order.reference_number }}
                            </h5>
                            <h6 class="card-subtitle mb-2 text-muted">Ordered on: {{ order.ordered_date }}</h6>
                        </div>
                        <hr/>

                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Total</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for item in order.items.all %}
                                    <tr>
                                        <td>{{ item.size.name }}, {{ item.colour.name }} of {{ item.product.title }}
                                            x {{ item.quantity }}</td>
                                        <td>${{ item.get_total_item_price }}</td>
                                    </tr>

                                {% endfor %}

                                <tr>
                                    <td>Subtotal</td>
                                    <td>${{ order.get_subtotal }}</td>
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td>${{ order.get_total }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
    <div class="site-sectino">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-m-12">
                    <h2 class="text-black">Tu perfil</h2>
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title"> Correo electrónico {{ request.user.email }}</h6>
                            <h6 class="card-title"> Usuario {{ request.user.username }}</h6>
                            <a href="{% url 'account_logout' %}"><small class="float-right"> Cerrar Sesión </small></a>
                            <br>
                            <a href="{% url 'account_change_password' %}"><small class="float-right"> Cambiar
                                Contraseña </small></a>
                            <br>
                            <a href="{% url 'account_email' %}"><small class="float-right">Cambiar Correo
                                electronico</small></a>
                        </div>

                        <hr>
                        <div class="site-blocks-table">
                            <h5 class="card-title"> &nbsp &nbsp Tus ordenes </h5>
                        </div>
                        <div class="site-blocks-table">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Nro. De Referencia</th>
                                    <th>Fecha</th>
                                    <th>Total</th>
                                    <th>Estado de pago</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for order in orders %}
                                    <tr>
                                        <a href="{% url 'cart:order-detail' order.pk %}">
                                            <td>{{ order.reference_number }}</td>
                                        </a>
                                        <td>{{ order.orden_fecha }}</td>
                                        <td>{{ order.get_total }}</td>
                                        <td>{% if order.ordenn %}Pagado{% else %}No pagado{% endif %}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="4"> No has realizado ninguna compra</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>